### ISSUE TITLE
Uncomplete column_name change

### ISSUE THREAD

**Issue by mabuch** [scherers/UKBB_EMG_Analysis#2]
If line 259 is changed, line 258 needs to be changed as well (from `usage_rmsd` to `usage_total`). Please decide on one, and set it as default in both lines.

```
Traceback (most recent call last):
  File "emg_visualizer.py", line 688, in <module>
    gui = VisualizerWindow([])
  File "emg_visualizer.py", line 259, in __init__
    self.usg_man_select.current(self.dataMgr.usage_columns.index('"usage_total"'))
ValueError: '"usage_total"' is not in list
```

**Comment by scherers** [comment]
Sorry, I did not see the other thing to change.
I thought this one thing can be changed at one place ;)

I opt for `usage_total` as default, as there will be this column in all files generated with the latest version. Can you please do the required change?

**Comment by mabuch** [comment]
done
