### ISSUE TITLE
thresholdRMSD() does not guarantee delta-border

### ISSUE THREAD

**Issue by mabuch** [scherers/UKBB_EMG_Analysis#5]
I wanted to speed up the thresholdRMSD()-function. To verify it, I compared it to the given thresholdRMSD()-function. I then found, that the given implementation has an error. The "jumping" provided by `i += delta` makes it possible, that the delta-intervall after a threshold-crossing (downwards, to the normal/"ok" signal) might or most likely will be shorter than delta.

Test-Data to illustrate this:

```
import sys
import numpy as np
import matplotlib.pyplot as plt

def thresholdRMSD(rmsd_data, cutoff, delta):
    print ("RMSD Filter")
    i = 0
    index = np.zeros((1,len(rmsd_data)), dtype=int)[0]
    while i < (len(rmsd_data)):
        if (i>0) and (np.fmod(i,1000) < 0.001):
            sys.stdout.write("\r\t\t%d%%" % float((100.0*i)/len(rmsd_data)) )
            sys.stdout.flush()
        if rmsd_data[i] < cutoff:
            index[i] = 1
            i += 1
        else:
            index[max(i-delta, 0):i] = 0
            i += delta
    print ('\ndone')
    return index

def thresholdRMSD2(rmsd_data, cutoff, delta):
    print ("RMSD Filter")
    index = np.zeros((1,len(rmsd_data)), dtype=int)[0]
    index[rmsd_data<cutoff]=1
    idxdiff = np.diff(index)
    idx1 = np.nonzero(idxdiff<0)[0]
    for i in idx1:
        index[max(0,i+1-delta):i+1]=0
    idx2 = np.nonzero(idxdiff>0)[0]
    for i in idx2:
        index[i+1:min(len(index),i+1+delta)]=0
    return index


test_data = np.array([0,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,2,2,2,2,0,0,0,0,0,2,2,2,2,2,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0,0,0,0,0,0,0,0])
test_index = thresholdRMSD(test_data, 1, 5)
test_index2 = thresholdRMSD2(test_data, 1, 5)
plt.plot(range(0,len(test_data)),test_data,'b',range(0,len(test_data)),test_index,'r',range(0,len(test_data)),.9*test_index2,'g')
```

![thresholdrmsd-bug-plot](https://cloud.githubusercontent.com/assets/12037887/8387507/3e225930-1c59-11e5-83d2-8f8d72f3adfe.png)

The plot shows, that the red curve (index of the original) thresholdRMSD() might fall too quickly. I propose to fix this with the new function, which is also faster.
I did not replace it myself, because the behaviour will be changed (because the current version is buggy), and I wanted to inform you about that.

**Comment by scherers** [comment]
Well it makes a difference in your academic example, but I cannot see a significant difference in the real world application:

![rmsd_old_vs_new](https://cloud.githubusercontent.com/assets/591680/8403468/6a00547e-1e45-11e5-971e-cda3a6741181.png)

However I will replace the function, although I prefer for-loops over the compact slice-notation in the present scenario due to more transparency for our client ;)

**Comment by mabuch** [comment]
I know that there are differences, because I tested it on the first few minutes of "V41M03_nonmoving.csv", and the two result-vectors were not equal.
Attached is a real-life-example where the algorithm failed.
![thresholdrmsd-bug-plot2](https://cloud.githubusercontent.com/assets/12037887/8404134/e885151e-1e4a-11e5-8cfa-e2494dfc093f.png)
